# config.py

VIDEO_PATH = "path/to/your/video.mp4"
OUTPUT_DIR = "./output"
FRAME_INTERVAL = 1

BLOCK_SIZE = 8
GLOBAL_DIFF_ALPHA = 1.0
GLOBAL_DIFF_PERCENTILE = 80
LOCAL_DIFF_BETA = 1.0
GAUSSIAN_SIGMA = 1.5
MOTION_THRESHOLD = 20
HASH_CLUSTER_THRESHOLD = 20
SELECTION_STRATEGY = 'topk'

ENABLE_LOCAL_DIFF = False
ENABLE_GLOBAL_DIFF = True
USE_AUTO_INTERVAL = True
USE_OTSU_FOR_MOTION = True

TOP_K = 1
SCORE_THRESHOLD = 1.0
